language: objective-c
osx_image: xcode10.2
before_install:
- gem update fastlane --no-document
- gem update cocoapods --no-document
- pod repo update
- pod install
script:
- cd Example/
- fastlane ci
