language: objective-c
osx_image: xcode11.4
before_install:
- gem update fastlane --no-document
- gem update cocoapods --no-document
- pod repo update
script:
- cd Example/
- pod install
- fastlane ci
